# 量化实验配置 - Medium批次
experiment_name: default
technique: 量化
batch_level: medium

# 模型配置
model: /data1/zhaofanghan/.cache/huggingface/hub/DeepSeek-R1-Distill-Qwen-1.5B
device: [4]

# 推理配置
max_tokens: 100
temperature: 0.8
top_p: 0.95
batch_size: 4

# 性能测试配置
num_prompts: 10
warmup_iterations: 3
test_iterations: 5

# 输出配置
output_dir: results
save_results: true

# 量化配置
quantization_config:
  load_in_8bit: true
  load_in_4bit: false
  bnb_4bit_compute_dtype: float16
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: nf4
